[programs.devnet]
solana_app = "9sLG4qKC4XPjLcQ56kiJk6a2CrHnYaLYKUHBDuRf2HFz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/andrewgulik/.config/solana/id.json"

[scripts]
test = "node tests/solana-app.js" 
